[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


[lints]
workspace = true
