[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4", features = ["rustls-0_23"] }
hyper = { version = "1.6.0", features = ["http2"] }
hyper-rustls = "0.27.5"
rustls-pemfile = "2"
rustls = "0.23.25"
tokio = { version = "1.44.1" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

dotenv.workspace = true
reqwest.workspace = true
